name: pray # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A lectio divina prayer helper built with python # 79 char long summary
description: |
  Pray is a simple command line program to help you pray following the ancient
  practice of lectio divina. This timed session takes about 12 minutes and consists of 
  4 parts: (1) Lectio: read, (2) Meditatio: meditate, (3) Oratio: prayer and (4) Contemplatio: sit in silence.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


parts:
  pray:
    plugin: python
    python-version: python3
    source: .




apps:
  pray:
    command: bin/offlineimap
    plugs: [x11, unity7, pulseaudio, home, audio-playback]
    


